version: '2'
services:
    plex:
        image: linuxserver/plex
        container_name: plex
        volumes:
            - /path/to/plex/config:/config
            - /path/to/plex/Movies:/data/movies
            - /path/to/plex/Shows:/data/tvshows
            - /path/to/plex/transcode:/data/transcode
        network_mode: host
        restart: unless-stopped
        environment:
            - VERSION=docker
            - TZ=America/New_York
            - PUID=1000
            - PGID=1000
    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /path/to/sonarr/config:/config
            - /path/to/nzbget/downloads:/downloads
            - /path/to/plex/Shows:/tv
        environment:
            - TZ=America/New_York
        ports:
            - 8989:8989
            - PUID=1000
            - PGID=1000
    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /path/to/radarr/config:/config
            - /path/to/nzbget/downloads:/downloads
            - /path/to/plex/Movies:/movies
        environment:
            - TZ=America/New_York
        ports:
            - 7878:7878
            - PUID=1000
            - PGID=1000
    portainer:
        image: portainer/portainer
        container_name: portainer
        ports:
            - 9000:9000
            - 8000:8000
        volumes:
            - /path/to/portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
    